/*
-- Query: SELECT * FROM questura.documenti ORDER BY nome
LIMIT 0, 1000

-- Date: 2016-05-03 16:02
*/
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('IDENT','CARTA DI IDENTITA\'',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CIDIP','CARTA ID. DIPLOMATICA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('IDELE','CARTA IDENTITA\' ELETTRONICA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CERID','CERTIFICATO D\'IDENTITA\'',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PASSE','PASSAPORTO DI SERVIZIO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PASDI','PASSAPORTO DIPLOMATICO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PASOR','PASSAPORTO ORDINARIO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PATEN','PATENTE DI GUIDA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PATNA','PATENTE NAUTICA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PORM5','PORTO D\'ARMI GUARDIE GIUR',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PORM3','PORTO D\'ARMI USO SPORTIVO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PORM2','PORTO FUCILE DIF. PERSON.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PORM1','PORTO FUCILE USO CACCIA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PORM4','PORTO PISTOLA DIF. PERSON',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TENAV','TES. ENTE NAZ. ASSIS.VOLO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TFEXD','TES. FERROV. EX DEPUTATI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TFERD','TES. FERROVIARIA DEPUTATI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESPT','TES. POSTE E TELECOMUNIC.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TECAM','TES. UNICO PER LA CAMERA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEDOG','TES.DOGANALE RIL.MIN.FIN.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CFMIL','TESS. AG. E AG.SC. C.F.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PPAGE','TESS. AGENTI/ASS.TI P.P.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSAPP','TESS. AGENTI/ASS.TI P.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('ACMIL','TESS. APP.TO AG.CUSTODIA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CCMIL','TESS. APP.TO CARABINIERI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('GFMIL','TESS. APP.TO FINANZIERE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VIMIL','TESS. APP.TO/VIG. URBANO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VVMIL','TESS. APP.TO/VIG. VV.FF.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESCS','TESS. CONSIGLIO DI STATO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESCA','TESS. CORTE D\'APPELLO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TECOC','TESS. CORTE DEI CONTI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEFSE','TESS. FERROV. SENATO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSFUN','TESS. FUNZIONARI P.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TETEL','TESS. IDENTIF.TELECOM IT.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEAMC','TESS. ISCR. ALBO MED/CHI.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEAOD','TESS. ISCRIZ. ALBO ODONT.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PPISP','TESS. ISPETTORI P.P.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSISP','TESS. ISPETTORI P.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESEA','TESS. MEMBRO EQUIP. AEREO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('MMMIL','TESS. MILIT. M.M.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('SDMIL','TESS. MILIT. TRUPPA SISMI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('EIMIL','TESS. MILITARE E.I.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TENAT','TESS. MILITARE NATO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('AMMIL','TESS. MILITARE TRUPPA A.M',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESAE','TESS. MIN. AFFARI ESTERI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMB','TESS. MIN.BEN.E ATT.CULT.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEMPI','TESS. MIN.PUBB.ISTRUZIONE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMN','TESS. MINIST. TRASP/NAVIG',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMD','TESS. MINISTERO DIFESA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMF','TESS. MINISTERO FINANZE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMG','TESS. MINISTERO GIUSTIZIA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMI','TESS. MINISTERO INTERNO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESLP','TESS. MINISTERO LAVORI PU',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMS','TESS. MINISTERO SANITA\'',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESMT','TESS. MINISTERO TESORO',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESOG','TESS. ORDINE GIORNALISTI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PARLA','TESS. PARLAMENTARI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('MAGIS','TESS. PERS. MAGISTRATI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('GFTRI','TESS. POL. TRIB. G.D.F.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSFEM','TESS. POLIZIA FEMMINILE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESPC','TESS. PRES.ZA CONS. MIN.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESPI','TESS. PUBBLICA ISTRUZIONE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('DESIS','TESS. S.I.S.D.E.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('ACSOT','TESS. SOTT.LI AG.CUSTODIA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('GFSOT','TESS. SOTT.LI G.D.F.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VISOT','TESS. SOTT.LI VIG. URBANI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VVSOT','TESS. SOTTUFF.LI VV.FF.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('AMSOT','TESS. SOTTUFFICIALI A.M.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CCSOT','TESS. SOTTUFFICIALI CC',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('EISOT','TESS. SOTTUFFICIALI E.I.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('SDSOT','TESS. SOTTUFFICIALI SISMI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CFSOT','TESS. SOTTUFICIALI C.F.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('MMSOT','TESS. SOTTUFICIALI M.M.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PPSOV','TESS. SOVRINTENDENTI P.P.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSSOT','TESS. SOVRINTENDENTI P.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('ACUFF','TESS. UFF.LI AG.CUSTODIA',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VIUFF','TESS. UFF.LI VIG.URBANI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CCUFF','TESS. UFFICIALE',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('AMUFF','TESS. UFFICIALI A.M.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('CFUFF','TESS. UFFICIALI C.F.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('EIUFF','TESS. UFFICIALI E.I.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('GFUFF','TESS. UFFICIALI G.D.F.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('MMUFF','TESS. UFFICIALI M.M.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PPUFF','TESS. UFFICIALI P.P.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('PSUFF','TESS. UFFICIALI P.S.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('SDUFF','TESS. UFFICIALI SISMI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('VVUFF','TESS. UFFICIALI VV.FF.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESIN','TESS.ISCR. ALBO INGEGNERI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESAR','TESS.ISCR.ALBO ARCHITETTI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TEPOL','TESS.MIN.POLIT.AGRIC.FOR.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESNO','TESSERA DELL\'ORDINE NOTAI',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESAV','TESSERA ISCR. ALBO AVVOC.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESDI','TESSERA RICONOSC. D.I.A.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('TESUN','TESSERA U.N.U.C.I.',NULL);
INSERT INTO `documenti` (`codice`,`nome`,`validator`) VALUES ('RIFUG','TITOLO VIAGGIO RIF.POLIT.',NULL);
